# Auto-generated by builder/map_channel.py — registry only.
# Edit builder/entries/my-portfolio/* for chart content; re-run Surface Interval to refresh wiki.
P_AUTO = [
    dict(
        slug="choi-convex",
        note="builder/entries/my-portfolio/choi-convex.md",
        title="ConvEx: A Visual Conversation Exploration System for",
        venue="unknown",
        year=2026,
        status="inferred",
        pdfs=["choi-convex.pdf"],
        themes=[],
        one="Auto-mapped from PDF — confirm themes and abstract.",
        flag="Auto-mapped by SCUBA — assign themes and verify metadata.",
        entry="builder/entries/my-portfolio/choi-convex.md",
    ),
    dict(
        slug="cscw2024-positive-reinforcement",
        note="builder/entries/my-portfolio/cscw2024-positive-reinforcement.md",
        title="“Positive reinforcement helps breed positive behavior”:",
        venue="unknown",
        year=2024,
        status="inferred",
        pdfs=["cscw2024_positive_reinforcement.pdf"],
        themes=[],
        one="Auto-mapped from PDF — confirm themes and abstract.",
        flag="Auto-mapped by SCUBA — assign themes and verify metadata.",
        entry="builder/entries/my-portfolio/cscw2024-positive-reinforcement.md",
    ),
]
