# Auto-generated by builder/map_channel.py — registry only.
# Edit builder/entries/lit-review/* for chart content; re-run Surface Interval to refresh wiki.
S_AUTO = [
    dict(
        slug="test-paper",
        entry="builder/entries/lit-review/test-paper.md",
        title="Test lit paper",
        source_file="raw/literature/test-paper.md",
        source_type="paper",
        channel="lit-review",
        status="staged",
        date_ingested="2026-06-19",
        one="Docked artifact — fill entry note; LLM Deep Dive pending.",
        flag="Edit builder/entries/lit-review/test-paper.md — generative sections via Deep Dive later.",
    ),
]
