#!/usr/bin/env python3
"""Map docked artifacts in raw/ to chart entries (builder/entries/) — never raw/notes.

Scans a channel's raw_path, creates deterministic entry files from templates, and
updates the auto registry (auto_papers.py or auto_sources.py).

    python3 builder/map_channel.py --channel my-portfolio
    python3 builder/map_channel.py --channel lit-review --vault /path/to/vault
"""
import datetime
import os
import re
import subprocess
import sys

BUILDER_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BUILDER_DIR)

from templates_util import entry_rel_path
from quick_dip import build_quick_dip_entry, extract_pdf, extract_text_file
from docks_util import load_channel_map, get_dock


def _channels(vault):
    return load_channel_map(vault)


def _channel_cfg(vault, channel_id):
    ch = _channels(vault).get(channel_id)
    if not ch:
        sys.exit("Unknown channel: {}".format(channel_id))
    return ch


def _load_data(vault):
    import importlib.util
    data_path = os.path.join(vault, "builder", "data.py")
    if not os.path.exists(data_path):
        sys.exit("No builder/data.py in vault: {}".format(vault))
    spec = importlib.util.spec_from_file_location("data", data_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod, os.path.join(vault, "builder")


def _load_auto(builder_dir, auto_file, auto_key):
    auto_path = os.path.join(builder_dir, auto_file)
    if not os.path.exists(auto_path):
        return []
    import importlib.util
    spec = importlib.util.spec_from_file_location("auto_mod", auto_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return list(getattr(mod, auto_key, []))


def _known_source_files(entries, key="source_file"):
    known = set()
    for e in entries:
        if key == "pdfs":
            for sf in e.get("pdfs", []):
                if sf:
                    known.add(sf)
                    known.add(os.path.basename(sf))
            continue
        sf = e.get(key)
        if not sf:
            continue
        known.add(sf)
        known.add(os.path.basename(sf))
    return known


def _slugify(name):
    base = os.path.splitext(name)[0].lower()
    base = re.sub(r"[^a-z0-9]+", "-", base).strip("-")
    return base or "artifact"


def _extract_artifact(fpath, ext):
    if ext == ".pdf":
        return extract_pdf(fpath)
    if ext in (".md", ".txt"):
        return extract_text_file(fpath)
    return {"title": "", "abstract": "", "venue": "", "year": None}


def _write_quick_dip_entry(vault, channel_id, slug, extracted, dry_run=False):
    rel = entry_rel_path(channel_id, slug)
    if dry_run:
        return rel
    abs_path = os.path.join(vault, rel)
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)
    body = build_quick_dip_entry(extracted)
    with open(abs_path, "w") as f:
        f.write(body)
    return rel


def _write_auto(builder_dir, entries, auto_file, auto_key, channel_id):
    path = os.path.join(builder_dir, auto_file)
    lines = [
        "# Auto-generated by builder/map_channel.py (Quick Dip registry).",
        "# Deep Dive: enrich builder/entries/ and builder/deepdives/ — then re-run Update chart.",
        "{} = [".format(auto_key),
    ]
    for e in entries:
        lines.append("    dict(")
        for key, val in e.items():
            if isinstance(val, str):
                lines.append('        {}="{}",'.format(key, val.replace('"', "'")))
            elif isinstance(val, int):
                lines.append("        {}={},".format(key, val))
            elif isinstance(val, list):
                inner = ", ".join('"{}"'.format(x) for x in val) if val else ""
                lines.append("        {}=[{}],".format(key, inner))
            elif val is None:
                lines.append("        {}=None,".format(key))
        lines.append("    ),")
    lines.append("]")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def _merge_auto_sources(builder_dir, channel_id, new_entries, auto_file, auto_key):
    """Keep entries from other channels in shared auto_sources.py."""
    existing = _load_auto(builder_dir, auto_file, auto_key)
    others = [e for e in existing if e.get("channel") != channel_id]
    merged = others + new_entries
    _write_auto(builder_dir, merged, auto_file, auto_key, channel_id)


def _refresh_stale_quick_dip(vault, channel_id, entries, dry_run=False):
    """Re-extract PDF facts for legacy inferred/scaffold entries."""
    cfg = _channel_cfg(vault, channel_id)
    raw_path = cfg["raw_path"]
    refreshed = []
    changed = False
    for e in entries:
        entry_text = _read_entry_text(vault, e.get("entry", ""))
        stale = (
            e.get("status") in ("inferred", "scaffolded")
            or e.get("venue") == "unknown"
            or "Auto-mapped" in (e.get("one") or "")
            or "theme-slug" in entry_text
            or "abstracting with credit" in entry_text.lower()
            or "ing with credit is permitted" in entry_text.lower()
            or "who are often Facebook" in entry_text
        )
        if not stale:
            refreshed.append(e)
            continue
        pdfs = e.get("pdfs", [])
        if not pdfs:
            refreshed.append(e)
            continue
        rel_source = pdfs[0]
        if "/" not in rel_source:
            rel_source = "{}/{}".format(raw_path, rel_source)
        fpath = os.path.join(vault, rel_source)
        if not os.path.exists(fpath):
            refreshed.append(e)
            continue
        ext = os.path.splitext(fpath)[1].lower()
        extracted = _extract_artifact(fpath, ext)
        title = extracted.get("title") or e.get("title", e["slug"])
        entry_rel = _write_quick_dip_entry(vault, channel_id, e["slug"], extracted, dry_run)
        e = dict(e)
        e.update({
            "entry": entry_rel,
            "note": entry_rel,
            "title": title[:200],
            "venue": extracted.get("venue") or "",
            "year": extracted.get("year") if extracted.get("year") is not None else 0,
            "status": "quick-dip",
            "themes": [],
            "one": "",
            "flag": "Quick dip — run Deep Dive to add themes, one-liner, and analysis.",
        })
        refreshed.append(e)
        changed = True
        print("  refresh quick-dip: {} (venue={} year={})".format(
            e["slug"], e.get("venue") or "—", e.get("year") or "—"))
    return refreshed, changed


def _read_entry_text(vault, entry_rel):
    if not entry_rel:
        return ""
    path = entry_rel if entry_rel.startswith(("builder/", "raw/")) else os.path.join(
        "builder/entries", entry_rel)
    abs_path = os.path.join(vault, path.replace("\\", "/"))
    if not os.path.exists(abs_path):
        return ""
    with open(abs_path) as f:
        return f.read()


def _backfill_entries(vault, channel_id, entries, dry_run=False):
    """Migrate legacy raw/notes references to builder/entries/."""
    changed = False
    for e in entries:
        entry_rel = e.get("entry") or ""
        if entry_rel.startswith("builder/entries"):
            continue
        slug = e["slug"]
        pdfs = e.get("pdfs", [])
        rel_source = pdfs[0] if pdfs else ""
        if rel_source and "/" not in rel_source:
            cfg = _channels(vault).get(channel_id, {})
            rel_source = "{}/{}".format(cfg.get("raw_path", "raw/papers"), rel_source)
        title = e.get("title", slug)
        extracted = {"title": title, "abstract": "", "venue": "", "year": None}
        if rel_source.lower().endswith(".pdf"):
            extracted = extract_pdf(os.path.join(vault, rel_source))
            if not extracted.get("title"):
                extracted["title"] = title
        new_rel = _write_quick_dip_entry(vault, channel_id, slug, extracted, dry_run)
        e["entry"] = new_rel
        e["note"] = new_rel
        changed = True
        print("  backfill: {} → {}".format(slug, new_rel))
    return entries, changed


def map_channel(vault, channel_id, dry_run=False):
    cfg = _channels(vault).get(channel_id)
    if not cfg:
        sys.exit("Unknown channel: {}".format(channel_id))

    data, builder_dir = _load_data(vault)
    auto_file = cfg["auto_file"]
    auto_key = cfg["auto_key"]
    raw_path = cfg["raw_path"]
    profile = cfg["profile"]

    auto = _load_auto(builder_dir, auto_file, auto_key)
    if profile == "portfolio":
        if auto_file == "auto_lab_papers.py":
            channel_auto = list(auto)
        else:
            channel_auto = [e for e in auto if e.get("channel", "my-portfolio") == channel_id]
        manual = list(data.P)
        if channel_id == "lab-portfolio":
            manual = [p for p in manual if any("lab/" in x for x in p.get("pdfs", []))]
        elif channel_id == "my-portfolio":
            manual = [p for p in manual if p.get("channel", "my-portfolio") == "my-portfolio"
                      and not any("lab/" in x for x in p.get("pdfs", []))]
        else:
            manual = [p for p in manual if p.get("channel") == channel_id]
        channel_auto, backfilled = _backfill_entries(vault, channel_id, channel_auto, dry_run)
        channel_auto, refreshed = _refresh_stale_quick_dip(vault, channel_id, channel_auto, dry_run)
        if (backfilled or refreshed) and not dry_run:
            _write_auto(builder_dir, channel_auto, auto_file, auto_key, channel_id)
        all_entries = manual + channel_auto
        known = _known_source_files(all_entries, "pdfs")
        for p in all_entries:
            for pdf in p.get("pdfs", []):
                known.add(pdf)
                known.add(os.path.basename(pdf))
    else:
        channel_auto = [e for e in auto if e.get("channel") == channel_id]
        all_entries = channel_auto
        known = _known_source_files(channel_auto)

    raw_dir = os.path.join(vault, raw_path)

    if not os.path.isdir(raw_dir):
        return []

    exts = set(cfg["extensions"])
    unmapped = []
    for f in sorted(os.listdir(raw_dir)):
        ext = os.path.splitext(f)[1].lower()
        if ext not in exts:
            continue
        rel = "{}/{}".format(raw_path, f).replace("\\", "/")
        if f in known or rel in known:
            continue
        unmapped.append(f)

    if not unmapped:
        return []

    new_entries = []
    existing_slugs = {e.get("slug") for e in all_entries}

    for fname in unmapped:
        fpath = os.path.join(raw_dir, fname)
        rel_source = "{}/{}".format(raw_path, fname).replace("\\", "/")
        ext = os.path.splitext(fname)[1].lower()
        extracted = _extract_artifact(fpath, ext)
        title = (extracted.get("title") or "")[:200]
        slug = _slugify(fname if title else fname)
        if not title:
            slug = _slugify(fname)
        if channel_id != "my-portfolio" and profile == "portfolio":
            slug = channel_id.replace("-", "")[:3] + "-" + slug
        if slug in existing_slugs:
            slug = slug + "-" + str(len(existing_slugs) + len(new_entries))
        existing_slugs.add(slug)

        entry_rel = _write_quick_dip_entry(vault, channel_id, slug, extracted, dry_run)

        if profile == "portfolio":
            pdfs = [rel_source] if channel_id != "my-portfolio" else [fname]
            year = extracted.get("year")
            entry = {
                "slug": slug,
                "entry": entry_rel,
                "note": entry_rel,
                "title": title,
                "venue": extracted.get("venue") or "",
                "year": year if year is not None else 0,
                "status": "quick-dip",
                "pdfs": pdfs,
                "themes": [],
                "one": "",
                "flag": "Quick dip — run Deep Dive to add themes, one-liner, and analysis.",
                "channel": channel_id,
            }
        else:
            entry = {
                "slug": slug,
                "entry": entry_rel,
                "title": title,
                "source_file": rel_source,
                "source_type": cfg.get("source_type", "note"),
                "channel": channel_id,
                "status": "quick-dip",
                "date_ingested": datetime.date.today().isoformat(),
                "one": "",
                "flag": "Quick dip — run Deep Dive to enrich this artifact.",
            }
        new_entries.append(entry)
        print("  quick-dip: {} → {} (title={!r:.50})".format(
            fname, slug, title or "(empty — add in Deep Dive)"))

    if dry_run:
        return new_entries

    if profile == "portfolio":
        merged = channel_auto + new_entries
        _write_auto(builder_dir, merged, auto_file, auto_key, channel_id)
    else:
        merged_channel = channel_auto + new_entries
        _merge_auto_sources(builder_dir, channel_id, merged_channel, auto_file, auto_key)

    return new_entries


def main():
    vault = os.path.dirname(BUILDER_DIR)
    dry_run = "--dry-run" in sys.argv
    channel_id = "my-portfolio"

    if "--vault" in sys.argv:
        vault = os.path.abspath(sys.argv[sys.argv.index("--vault") + 1])
    if "--channel" in sys.argv:
        channel_id = sys.argv[sys.argv.index("--channel") + 1]

    if subprocess.call(["which", "pdftotext"], stdout=subprocess.DEVNULL) != 0:
        print("warning: pdftotext not found — PDF title/abstract/venue extraction unavailable")

    print("channel: {}".format(channel_id))
    mapped = map_channel(vault, channel_id, dry_run=dry_run)
    if mapped:
        print("quick-dip: {} artifact(s) → builder/entries/{}".format(len(mapped), channel_id))
    else:
        cfg = _channel_cfg(vault, channel_id)
        print("no unmapped files in {}".format(cfg["raw_path"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
